version: "3.3"
services:
  apinit:
    container_name: apinit
    image: golanginit
    environment:
      - LOCAL=DEV
    build: "./"
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
  mysql:
    container_name: apinit-sql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "apinit_go"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
