version: "3.3"
services:

#NGINX
  nginx:
    container_name: apinit-api-nginx
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "apinit"
#API
  apinit:
    container_name: apinit-api-golang
    image: golanginit
    environment:
      - LOCAL=DEV
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
#MYSQL     
  mysql:
    container_name: apinit-sql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "apinit_go"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
